name: Production Build

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yarn install dependencies
        run: yarn install

      - name: yarn build & deploy to gh-pages
        run: yarn deploy
