name: Production Build

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: yarn install dependencies
      #   run: yarn install
      # - name: yarn build
      #   run: yarn build
      - name: echo
        run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        # env:
        #   GH_EVENT: ${{ github.event }}
      # - name: yarn deploy to gh-pages
      #   run: yarn deploy -u ${{ github.event.pusher.email }}
